CREATE MASTER KEY ENCRYPTION BY
PASSWORD= '123'

CREATE CERTIFICATE certificate
WITH SUBJECT = '123';

CREATE SYMMETRIC KEY symmetric_key
WITH ALGORITHM = AES_256
ENCRYPTION BY CERTIFICATE certificate;

OPEN SYMMETRIC KEY symmetric_key
DECRYPTION BY CERTIFICATE certificate;

DROP SYMMETRIC KEY symmetric_key 